id: hard_leather_mask
type: item
guid: 505a989ac6b578095aed926fe8bb08db
name: Hard Leather Mask
internal_name: Helm04 Hard Leather Armor Unit
parse_name: Helm04HardLeatherArmorUnit

category: armours
slot: helm
material: hard_leather
tier: 4
rarity: variable

spawn_level:
  min: 4
  max: 6

stat_level:
  min: 4
  max: 4

item_level:
  max: 100

grades:
  armor:
    min: 0.75
    max: 1.0
    max_grade: 10
  damage:
    min: 0.0
    max: 0.0
    max_grade: 10

inventory:
  size: [2, 2]
  stackable: false

loot:
  weight: 100

combat:
  damage_range: 0
  damage_type: null

description: >
  Base helm blueprint item.

flavor_text: >
  I could run full tilt into a tree with this on!

sell_price: null
image: images/items/armours/helm/Helm04_Hard_Leather.png

stats:
  base:
    armor: null
    block: null
    resistances: {}
  scaling:
    per_tier: {}
    per_item_level: {}
    grade_scaling:
      armor_grade_range: [0.75, 1.0]
      damage_grade_range: [0.0, 0.0]
  affix_slots: []

game_version: 0.0.23471
last_updated: 2026-02-28
status: active
tags:
  - items
  - armours
  - helm
  - hard_leather
